##  NumPy Introduction (Theory)

NumPy (Numerical Python) is a core Python library used for fast and efficient numerical computing. It mainly provides support for working with arrays, especially multi-dimensional arrays, along with a wide range of mathematical functions.

It is widely used in data science, machine learning, artificial intelligence, and scientific computing because it performs operations much faster than normal Python lists.

NumPy also serves as the foundation for many other important libraries like Pandas, SciPy, and Scikit-learn.

In simple terms, NumPy helps us handle large amounts of numerical data in an optimized and structured way.


### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [78]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [79]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [80]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [82]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [83]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [84]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
# np.random
np.random.random((3,4))

array([[0.8021799 , 0.443891  , 0.58466855, 0.01023553],
       [0.14650668, 0.44010181, 0.53782423, 0.75683966],
       [0.9898468 , 0.33482034, 0.09331496, 0.67314473]])

In [87]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [88]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [89]:
a1 = np.arange(12,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [90]:
# ndim
a3.ndim

3

In [91]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [93]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [94]:
# itemsize
a3.itemsize

8

In [95]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [96]:
# astype
a3.astype(np.int32)
q = a3.astype(np.int32)
a3.astype(np.int8)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int8)

### Array Operations

In [97]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [98]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [99]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [101]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[16., 68., 88.],
       [83., 43., 78.],
       [11., 21., 57.]])

In [102]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 14608.,  61404., 391248.])

In [103]:
# mean/median/std/var
np.var(a1,axis=1)

array([920.88888889, 316.66666667, 390.22222222])

In [104]:
# trigonomoetric functions
np.sin(a1)

array([[-0.28790332, -0.89792768,  0.0353983 ],
       [ 0.96836446, -0.83177474,  0.51397846],
       [-0.99999021,  0.83665564,  0.43616476]])

In [105]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [106]:
# log and exponents
np.exp(a1)

array([[8.88611052e+06, 3.40427605e+29, 1.65163625e+38],
       [1.11286375e+36, 4.72783947e+18, 7.49841700e+33],
       [5.98741417e+04, 1.31881573e+09, 5.68572000e+24]])

In [107]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[76., 76., 21.],
       [77., 56.,  5.]])

### Indexing and Slicing

In [108]:
a1 = np.arange(14)
a2 = np.arange(18).reshape(6,3)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [109]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [110]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
a2[1,0]

np.int64(3)

In [112]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [113]:
a3[1,0,1]

np.int64(5)

In [114]:
a3[1,1,0]

np.int64(6)

In [115]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [116]:
a1[2:5:2]

array([2, 4])

In [117]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
a2[0:2,1::2]

array([[1],
       [4]])

In [119]:
a2[::2,1::2]

array([[ 1],
       [ 7],
       [13]])

In [120]:
a2[1,::3]

array([3])

In [121]:
a2[0,:]

array([0, 1, 2])

In [122]:
a2[:,2]

array([ 2,  5,  8, 11, 14, 17])

In [123]:
a2[1:,1:3]

array([[ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]])

In [124]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
a3[1,:3]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [126]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [127]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [128]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [129]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13


In [130]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [131]:
for i in a2:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]


In [132]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [134]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [135]:
# reshape

In [136]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [143]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [144]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

ravel() in NumPy is used to convert a multi-dimensional array into a 1D array.

### Stacking

In NumPy, stacking means joining or combining multiple arrays together.

There are mainly 3 types of stacking:
1-horizontal

2-vertical

3-Depth Stacking (dstack)

Arrays are joined along the third dimension (depth).

a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.dstack((a,b))

Output:

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Shape:

(2, 2, 2)

In [138]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [147]:
a8=np.array([1,2,3,4])
a9=np.array([5,6,7,8])
np.hstack((a8,a9))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
np.vstack((a8,a9))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [151]:
np.stack((a8,a9),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

axis=0 → stack row-wise

axis=1 → stack column-wise

In [140]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [141]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting

In [145]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [165]:
np.vsplit(a5,1
          )

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [164]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]