### np.sort

Return a sorted copy of an array.


In [76]:

import numpy as np
a = np.random.randint(1,100,15)
a

array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

In [77]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[77, 53, 28, 75],
       [34,  2, 47, 77],
       [ 8, 97, 45, 62],
       [73,  3, 81, 91],
       [47, 15, 11, 59],
       [12,  6, 42, 89]])

In [78]:
#descending order
np.sort(a)[::-1]

array([99, 97, 96, 94, 86, 83, 79, 68, 65, 60, 56, 22,  6,  3,  1])

In [79]:
np.sort(b,axis=0) #column wise sorting

array([[ 8,  2, 11, 59],
       [12,  3, 28, 62],
       [34,  6, 42, 75],
       [47, 15, 45, 77],
       [73, 53, 47, 89],
       [77, 97, 81, 91]])

In [80]:
np.sort(b,axis=1) #row wise sorting

array([[28, 53, 75, 77],
       [ 2, 34, 47, 77],
       [ 8, 45, 62, 97],
       [ 3, 73, 81, 91],
       [11, 15, 47, 59],
       [ 6, 12, 42, 89]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array


In [81]:

np.append(a,200)

array([ 94,  22,  65,  97,  86,  60,   6,  96,  83,   1,  79,   3,  56,
        68,  99, 200])

In [82]:
b

array([[77, 53, 28, 75],
       [34,  2, 47, 77],
       [ 8, 97, 45, 62],
       [73,  3, 81, 91],
       [47, 15, 11, 59],
       [12,  6, 42, 89]])

In [83]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[77.        , 53.        , 28.        , 75.        ,  0.41041224],
       [34.        ,  2.        , 47.        , 77.        ,  0.31697155],
       [ 8.        , 97.        , 45.        , 62.        ,  0.89333535],
       [73.        ,  3.        , 81.        , 91.        ,  0.1449641 ],
       [47.        , 15.        , 11.        , 59.        ,  0.84339776],
       [12.        ,  6.        , 42.        , 89.        ,  0.16474742]])

This code creates one random number for each row and adds those numbers as a new column to array b

In [84]:
b

array([[77, 53, 28, 75],
       [34,  2, 47, 77],
       [ 8, 97, 45, 62],
       [73,  3, 81, 91],
       [47, 15, 11, 59],
       [12,  6, 42, 89]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.


In [85]:

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [86]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [140]:
a=([1,2])
b=([3])
np.concatenate((a,b),axis=0)


array([1, 2, 3])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.


In [88]:

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [89]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array



In [143]:
a = np.random.randint(1,100,15)
a
a.shape

(15,)

In [144]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [145]:
np.expand_dims(a,axis=1)

array([[ 1],
       [53],
       [88],
       [47],
       [ 3],
       [28],
       [50],
       [89],
       [95],
       [91],
       [61],
       [52],
       [67],
       [ 5],
       [ 9]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.


In [93]:
a

array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

In [94]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  4,  5,  7,  8, 10, 12, 13, 14]),)

In [95]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 22,  0,  0,  0,  0,  6,  0,  0,  1,  0,  3,  0,  0,  0])

In [96]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 65, 97,  0,  0,  0,  0, 83,  1, 79,  3,  0,  0, 99])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.


In [147]:

a

array([ 1, 53, 88, 47,  3, 28, 50, 89, 95, 91, 61, 52, 67,  5,  9])

In [148]:
np.argmax(a)

np.int64(8)

In [149]:
b

[3]

In [161]:
np.argmax(b,axis=0)

array([1, 0, 0, 2])

In [159]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[74, 91, 83, 70],
       [91, 17, 62, 34],
       [81, 48, 33, 72],
       [19,  3, 43, 70],
       [18, 79, 64, 46],
       [71, 76, 78, 32]])

In [160]:
# np.argmin
np.argmin(a)

np.int64(0)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.


In [153]:
a

array([ 1, 53, 88, 47,  3, 28, 50, 89, 95, 91, 61, 52, 67,  5,  9])

In [154]:
np.cumsum(a)

array([  1,  54, 142, 189, 192, 220, 270, 359, 454, 545, 606, 658, 725,
       730, 739])

In [156]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[23, 74, 51,  9],
       [67,  3, 71, 65],
       [45, 68, 82,  4],
       [22,  6, 34,  9],
       [47, 77, 90,  2],
       [50, 27, 72, 70]])

In [157]:
np.cumsum(b,axis=1)

array([[ 23,  97, 148, 157],
       [ 67,  70, 141, 206],
       [ 45, 113, 195, 199],
       [ 22,  28,  62,  71],
       [ 47, 124, 214, 216],
       [ 50,  77, 149, 219]])

In [107]:
np.cumsum(b)

array([  77,  130,  158,  233,  267,  269,  316,  393,  401,  498,  543,
        605,  678,  681,  762,  853,  900,  915,  926,  985,  997, 1003,
       1045, 1134])

In [108]:
# np.cumprod
np.cumprod(a)

array([                 94,                2068,              134420,
                  13038740,          1121331640,         67279898400,
              403679390400,      38753221478400,    3216517382707200,
          3216517382707200,  254104873233868800,  762314619701606400,
       5796130555870855168, 6755252251317567488, 4687186226895323136])

In [109]:
a

array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.


In [110]:
a

array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

In [111]:
np.percentile(a,50)

np.float64(68.0)

In [112]:
np.median(a)

np.float64(68.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.



In [162]:
a

array([ 1, 53, 88, 47,  3, 28, 50, 89, 95, 91, 61, 52, 67,  5,  9])

In [163]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.


In [115]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [116]:
# code
a


array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

In [117]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.


In [118]:
# code
a

array([94, 22, 65, 97, 86, 60,  6, 96, 83,  1, 79,  3, 56, 68, 99])

In [119]:
np.flip(a)

array([99, 68, 56,  3, 79,  1, 83, 96,  6, 60, 86, 97, 65, 22, 94])

In [120]:
b

array([[77, 53, 28, 75],
       [34,  2, 47, 77],
       [ 8, 97, 45, 62],
       [73,  3, 81, 91],
       [47, 15, 11, 59],
       [12,  6, 42, 89]])

In [121]:
np.flip(b,axis=1)

array([[75, 28, 53, 77],
       [77, 47,  2, 34],
       [62, 45, 97,  8],
       [91, 81,  3, 73],
       [59, 11, 15, 47],
       [89, 42,  6, 12]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [167]:

a

array([110, 530,  88,  47,   3,  28,  50,  89,  95,  91,  61,  52,  67,
         5,   9])

In [166]:
np.put(a,[0,1],[110,530])
print(a)

[110 530  88  47   3  28  50  89  95  91  61  52  67   5   9]


### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.



In [124]:

a

array([110, 530,  65,  97,  86,  60,   6,  96,  83,   1,  79,   3,  56,
        68,  99])

In [125]:
np.delete(a,[0,2,4])

array([530,  97,  60,   6,  96,  83,   1,  79,   3,  56,  68,  99])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [168]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [169]:
np.intersect1d(m,n)

array([3, 4, 5])

In [170]:
np.setdiff1d(n,m)

array([6, 7])

In [171]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [172]:
m[np.in1d(m,1)]

/tmp/ipykernel_3838/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.


In [173]:

a

array([110, 530,  88,  47,   3,  28,  50,  89,  95,  91,  61,  52,  67,
         5,   9])

In [174]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 47, 25, 28, 50, 75, 75, 75, 61, 52, 67, 25, 25])